# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.11-alpine

WORKDIR /app

# Copy all project files into the image
COPY . /app/

# Adjust forest_fire_mcp_server.py to use a Linux-compatible data file path
RUN sed -i 's|C:/Users/user/Desktop/MCP/forest_fire_data.json|./forest_fire_data.json|g' forest_fire_mcp_server.py

# Install Python dependencies
RUN pip install --no-cache-dir -r requirements.txt

EXPOSE 8000

CMD ["python", "forest_fire_mcp_server.py"]
